### ISSUE TITLE
Gold rare border is missing

### ISSUE THREAD

**Issue by marlleyilson** [amarillonmc/MSE201_w_ygos10#2]
It only works in pendulum frames or without the image frame

![screenshot_1](https://user-images.githubusercontent.com/43358820/45656978-c2d39980-babe-11e8-9c08-14da16e53522.jpg)
![screenshot_4](https://user-images.githubusercontent.com/43358820/45656979-c2d39980-babe-11e8-8527-4064a0834faa.jpg)

**Comment by amarillonmc** [comment]
Issue noted and fixed in the latest commit.
Thank you for reporting. 

------------------------
Note that in "Actual Style", the borders may seem too thick, I personally don't have the need and time to make a better gold rare border, so it'll be left at that unless one is provided to me.
