### ISSUE TITLE
@ Symbol doesn't seem to work

### ISSUE THREAD

**Issue by AlanOC91** [amarillonmc/MSE201_w_ygos10#7]
Hi there, just downloaded this and tried to do the @Ignister monsters in it. I can see the commit saying the @ symbols are fixed but whenever I try it, it still shows as at.

Any ideas?

Also great work at keeping this updated!

**Comment by amarillonmc** [comment]
Try manually insert the symbol from the menu.
While the cursor is at the card name, go Font->Insert Symbol and click on the AT symbol.

However, this is only a temporary fix with quite some limitations so I'm not satisfied with that myself, I've updated the fonts to manually inserted the AT symbol in it, so before doing this, try re-installing the changed fonts (just install them and choose yes on the prompt).

**Comment by AlanOC91** [comment]
Re-installed fonts and re-tested to no avail but it works when I manually enter them from the toolbar. Since there aren't too many cards with @ in their name, it's not such a bad workaround.

Thanks!

**Comment by Hippsy** [comment]
I also can't seem to get the @ symbol to work. It either shows up as 'at' or it's replaced by an infinity symbol.

You have my thanks if I could get help fixing this.

**Comment by amarillonmc** [comment]
> While the cursor is at the card name, go Font->Insert Symbol and click on the AT symbol.

Don't type the @ symbol, use the above method.
