### ISSUE TITLE
Seems there is something missed

### ISSUE THREAD

**Issue by MorinoSakura** [amarillonmc/MSE201_w_ygos10#8]
![clipimage](https://user-images.githubusercontent.com/31189157/66253657-77119200-e79e-11e9-9d6f-7bddbafd6d78.jpg)

**Comment by amarillonmc** [comment]
已经补上原作者漏掉的仪式灵摆卡模（大概因为原游戏中没有仪式灵摆所以懒得做了吧。
重新pull下就行。
